const menu=document.querySelector('.menu'),nav=document.querySelector('.nav');
if(menu&&nav)menu.addEventListener('click',()=>{nav.classList.toggle('open');menu.setAttribute('aria-expanded',nav.classList.contains('open'))});
document.querySelectorAll('.nav a').forEach(a=>a.addEventListener('click',()=>nav?.classList.remove('open')));

const zh={
'Home':'首页','Products':'产品','Services':'服务','About':'关于我们','Contact':'联系我们','WhatsApp Us':'WhatsApp 联系','SYSTEM INTEGRATOR':'系统整合商',
'PENANG IT & SECURITY SYSTEM INTEGRATOR':'槟城 IT 与保安系统整合商','One Partner.':'一个伙伴。','Complete Systems.':'完整系统。','Built to Last.':'稳定耐用。','We plan, supply, install and support your IT, networking, CCTV, alarm, door access and ANPR systems as one connected solution.':'我们为企业规划、供应、安装及维护 IT、网络、CCTV、警报、门禁和 ANPR 系统，让所有系统稳定配合。','Get Free Onsite Assessment':'预约免费现场评估','Explore Our Systems':'查看我们的系统','Since 2003':'自 2003 年','Industry experience':'行业经验','Local Team':'本地团队','Fast Penang support':'槟城快速支援','One Integrator':'一个整合商','Plan · Install · Integrate':'规划 · 安装 · 整合',
'IT System':'IT 系统','Computers & Servers':'电脑与服务器','Network System':'网络系统','LAN, Wi-Fi & Cabling':'LAN、Wi‑Fi 与布线','CCTV System':'CCTV 监控系统','Monitor & Record':'监控与录像','Alarm System':'防盗警报系统','Detect & Alert':'侦测与通知','Door Access':'门禁系统','Control Every Entry':'管理每个出入口','ANPR System':'ANPR 车牌识别系统','Recognise Vehicles':'识别车辆',
'When one system fails, the whole operation feels it.':'一个系统出问题，整个生意都会受影响。','IT Downtime':'IT 停机','Network Down':'网络中断','Security Gaps':'保安漏洞','Unauthorised Access':'未经授权进入','PROFESSIONAL STRUCTURED CABLING · PENANG':'槟城专业结构化网络布线','Neat cabling today.':'今天布线整齐。','Stable business tomorrow.':'明天营运稳定。','Our trained technicians plan cable routes, pull CAT6 and fibre, terminate, label and test every connection—safely and professionally for commercial sites.':'我们的技术人员为商业场所规划线路、铺设 CAT6 与光纤、端接、标签和测试每个连接，安全又专业。','✓ Factory & Warehouse':'✓ 工厂与仓库','✓ Office & Data Room':'✓ 办公室与数据室','✓ Cafe & Retail':'✓ 咖啡店与零售店','✓ Condominium':'✓ 公寓管理','Book a Site Survey':'预约现场勘察','View Network Services':'查看网络服务',
'SIX CORE SYSTEMS':'六大核心系统','One team. Every system connected.':'一个团队，整合所有系统。','View system →':'查看系统 →','Networking System':'网络系统','Door Access System':'门禁系统','COMMERCIAL SYSTEMS FOR PENANG':'专为槟城商业场所打造','Designed around your environment.':'按照您的场所来设计。','FACTORY & WAREHOUSE':'工厂与仓库','CORPORATE OFFICE':'企业办公室','CAFE & RETAIL':'咖啡店与零售店','CONDOMINIUM & RESIDENCE MANAGEMENT':'公寓与物业管理','BUILT FOR PENANG COMMERCIAL SITES':'专为槟城商业场所设计','Technology that fits the way you operate.':'适合您营运方式的科技。','Factories':'工厂','Corporate Offices':'企业办公室','Warehouses':'仓库','Condominiums':'公寓','Cafes & Retail':'咖啡店与零售店','Clinics':'诊所','SERVICE COVERAGE':'服务地区','Penang Island & Mainland':'槟岛与威省','Kedah & Nearby Areas':'吉打及邻近地区','READY TO BUILD IT PROPERLY?':'准备把系统做好吗？','Let’s make every business system stable, secure and connected.':'让您的商业系统更稳定、更安全、连接更顺畅。','Book Free Onsite Assessment':'预约免费现场评估',
'BUSINESS SYSTEM PRODUCTS':'商业系统产品','Reliable products.':'可靠产品。','One complete system.':'一套完整系统。','Get Product Advice':'获取产品建议','PRODUCT CATEGORIES':'产品类别','Everything your business system needs.':'商业系统所需，一站备齐。','IT Equipment':'IT 设备','Network Equipment':'网络设备','Printers & Supplies':'打印机与耗材','Software & Licensing':'软件与正版授权','NOT SURE WHAT TO CHOOSE?':'不确定该选什么？','We recommend the right system—not just a product.':'我们推荐适合您的系统，不只是卖产品。','Ask Mobit Solution':'咨询 Mobit Solution',
'PLAN · SUPPLY · INSTALL · INTEGRATE · SUPPORT':'规划 · 供应 · 安装 · 整合 · 支援','Professional service.':'专业服务。','One responsible team.':'一个团队负责到底。','Book Onsite Assessment':'预约现场评估','Site Assessment':'现场评估','Understand your operation':'了解您的营运','System Planning':'系统规划','Design the right solution':'设计合适方案','Installation':'专业安装','Clean, professional work':'整齐、专业施工','Testing & Support':'测试与支援','Keep everything reliable':'确保系统稳定','OUR SYSTEM SERVICES':'我们的系统服务','From one problem to a complete solution.':'从解决一个问题，到建立完整方案。','IT System & Support':'IT 系统与支援','ONE SYSTEM INTEGRATOR':'一个系统整合商','No more calling different installers and wondering who is responsible.':'不必再找不同安装商，也不必担心谁来负责。',
'ABOUT MOBIT SOLUTION':'关于 MOBIT SOLUTION','Your local IT & Security System Integrator.':'您本地的 IT 与保安系统整合商。','Founder & System Integration Specialist':'创办人兼系统整合专家','MEET THE FOUNDER':'认识创办人','A lifelong passion for technology and complete business systems.':'热爱科技，专注打造完整商业系统。','YOUR LOCAL SYSTEM PARTNER':'您的本地系统伙伴','Plan it right once. Save costs for the long term.':'一次规划好，长期更省钱。','Talk to Mobit Ong':'联系 Mobit Ong',
'CONTACT MOBIT SOLUTION':'联系 MOBIT SOLUTION','Tell us which system you need.':'告诉我们您需要什么系统。','FASTEST WAY TO REACH US':'最快联系我们','WhatsApp Mobit Solution':'WhatsApp 联系 Mobit Solution','Call Us':'致电我们','COMPANY':'公司','CORE SYSTEMS':'核心系统','SERVICE AREA':'服务地区','Penang & Nearby Areas':'槟城及邻近地区','BUSINESS HOURS':'营业时间','Monday–Saturday':'星期一至星期六','Closed Sunday & Public Holidays':'星期日及公共假期休息','BOOK A SERVICE VISIT':'预约上门服务','Choose your preferred schedule.':'选择您方便的日期和时间。','Contact Name':'联系人姓名','Company Name':'公司名称','Contact Number':'联系电话','Required System / Service':'所需系统／服务','Preferred Date':'首选日期','Preferred Time':'首选时间','Select a time':'选择时间','Service Location':'服务地点','Problem / Request':'问题／需求','Send Booking via WhatsApp':'通过 WhatsApp 发送预约'
};
const original=new WeakMap();
function setLanguage(lang){
 document.documentElement.lang=lang==='zh'?'zh-Hans':'en';
 document.querySelectorAll('body *:not(script):not(style)').forEach(el=>[...el.childNodes].filter(n=>n.nodeType===3&&n.nodeValue.trim()).forEach(n=>{if(!original.has(n))original.set(n,n.nodeValue);const base=original.get(n),key=base.trim();n.nodeValue=lang==='zh'&&zh[key]?base.replace(key,zh[key]):base}));
 document.querySelectorAll('.lang-btn').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));localStorage.setItem('mobit-lang',lang)
}
const box=document.createElement('div');box.className='language-switch';box.innerHTML='<button class="lang-btn" data-lang="en">EN</button><span>/</span><button class="lang-btn" data-lang="zh">中文</button>';document.querySelector('.nav-cta')?.before(box);box.addEventListener('click',e=>{const b=e.target.closest('.lang-btn');if(b)setLanguage(b.dataset.lang)});setLanguage(localStorage.getItem('mobit-lang')||'en');

const form=document.querySelector('#booking-form');if(form){const date=form.querySelector('[name="date"]');if(date)date.min=new Date().toISOString().split('T')[0];form.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(form),lines=['Hi Mobit Solution, I would like to book a service appointment.','',`Name: ${d.get('name')}`,`Company: ${d.get('company')||'-'}`,`Contact: ${d.get('phone')}`,`System / Service: ${d.get('service')}`,`Preferred date: ${d.get('date')}`,`Preferred time: ${d.get('time')}`,`Location: ${d.get('location')}`,`Problem / Request: ${d.get('problem')||'-'}`,'','Please confirm whether this schedule is available. Thank you.'];window.open('https://wa.me/60124769358?text='+encodeURIComponent(lines.join('\n')),'_blank','noopener,noreferrer')})}
